### PR TITLE
Mastery exercise submission

### PR DESCRIPTION
**Pull request by danrday**

### CODE REVIEW

**Comment by morecallan** [comment]
@danrday are you ready for review?

**Comment by danrday** [comment]
@morecallan Sure! Was trying to get the hackerTyper to work but the basic reqs are there.

**Comment by morecallan** [comment]
@danrday Great start so far! I'll wait til you wrap up the hackertype to get fully into it BUT just a something you might want to look at:

Let the map() throw out any unmatched search terms. (right now you are passing them into the next Transform stream)

**Comment by danrday** [comment]
@morecallan Map() is now throwing out any unmatched search terms. Ready for any other reviews. Thanks for all your help!

**Comment by morecallan** [comment]
@danrday This is gorgeous. Major coolPoints for tackling the bonuses in a clear, clean way!

COMMENTS  then you can merge.

**Pull request merged**
